### ISSUE TITLE
Method db.collection.distinct is not implemented.

### ISSUE THREAD

**Issue by lala7573** [DataGrip/mongo-jdbc-driver#6]
Hi, I'm using DataGrip with mongodb driver and faced error 
```
Method db.collection.distinct is not implemented.
```
And found out it's really not implemented. 
https://github.com/DataGrip/mongo-jdbc-driver/blob/master/src/main/java/com/dbschema/mongo/nashorn/JMongoCollection.java#L66

Is there any plan to support this? and why doesn't it work?

**Comment by kornilova203** [comment]
Hello @lala7573,
Soon we will change our methods implementation to [mongodb-js/mongosh](https://github.com/mongodb-js/mongosh) and most of the methods will be supported. I believe it will happen within 2 weeks.

Though `distinct` method is a bit tricky but I think I will be able to make it work

**Comment by kornilova203** [comment]
The problem is that MongoDB did not provide a way to execute shell scripts outside the command-line shell.
But with [mongodb-js/mongosh](https://github.com/mongodb-js/mongosh) it will be possible. I currently work on Java wrapper for it.

**Comment by alexander-alegre** [comment]
Using the latest of DataGrip (2021.1.3) the issue is still present. Any update?

**Comment by kornilova203** [comment]
Hello @alexander-alegre,
I'll check next week if I can fix this issue

**Comment by kornilova203** [comment]
Hi all!
Sorry that it took so much time to fix the issue
I've implemented `distinct` operation, it will be in MongoDB driver soon
https://github.com/mongodb-js/mongosh/pull/1073

But there is a limitation unfortunately: all values should be of one type because Java driver for MongoDB requires you to specify type for value comparison. In my implementation I use type of the first value in a given field.
If there are different types, you'll see an error like `Invalid numeric type, found: STRING`.
Though you always can filter documents using second parameter in `distinct` function e.g. `db.collection.distinct('color', {type: 'plane'})`

**Comment by rahulroy9202** [comment]
Using the latest of DataGrip (2021.2.2) MongoDB Driver Version 1.12 the issue is still present. Any update? Thanks

**Comment by kornilova203** [comment]
It works for me:
![image](https://user-images.githubusercontent.com/23450724/138069633-babdf38a-391f-4405-a7fb-fabe89a2aa2b.png)

@rahulroy9202, could you please share a command that you run and an error that you get?

@GilbertOstlethwaite, you need to update driver. Go to data source connection page, choose `Drivers` and find MongoDB there:

![image](https://user-images.githubusercontent.com/23450724/138069915-bad015ab-53b1-4cf9-9cb9-7a32648578e8.png)

**Comment by rahulroy9202** [comment]
Hi @kornilova203  I have updated to 2021.2.4 since and tried distinct. It works for me now. 

![image](https://user-images.githubusercontent.com/3462467/138140585-4eb46ad1-bc2e-4106-844f-7af7444b3430.png)

**Comment by kornilova203** [comment]
@rahulroy9202,
Good!
For your information: usually you need to update drivers manually, they are not updated automatically with IDE updates.
It's because new drivers may have new bugs, and we want users to be aware of the fact that driver was changed.

**Comment by kornilova203** [comment]
Works as expected in driver v1.18.
If you still have any issues, please let me know here
<img width="919" alt="image" src="https://github.com/DataGrip/mongo-jdbc-driver/assets/23450724/b70fd792-aa4e-46ed-bade-dca764f64986">
